# Generated by Django 6.0.1 on 2026-02-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('health', models.IntegerField(default=100)),
                ('level', models.IntegerField(default=1)),
            ],
        ),
    ]
