# Generated by Django 6.0.1 on 2026-02-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_location_character_current_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('health', models.IntegerField(default=50)),
                ('attack_power', models.IntegerField(default=10)),
                ('xp_reward', models.IntegerField(default=20)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='strength',
            field=models.IntegerField(default=50),
        ),
    ]
