# Generated by Django 6.0.1 on 2026-02-02 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_enemy_character_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='current_enemy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.enemy'),
        ),
    ]
