# Generated by Django 6.0.1 on 2026-02-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_character_current_enemy'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
