# Generated by Django 6.0.1 on 2026-02-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_character_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='armor',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='character',
            name='gold_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='mana',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='enemy',
            name='armor',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='enemy',
            name='level',
            field=models.IntegerField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='enemy',
            name='magic_armor',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='enemy',
            name='mana',
            field=models.IntegerField(default=50),
        ),
    ]
