# Generated by Django 6.0.1 on 2026-02-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_character_armor_character_gold_amount_character_mana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='xp_reward',
            field=models.IntegerField(default=20),
        ),
    ]
