# Generated by Django 6.0.1 on 2026-02-06 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_quest_xp_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='game.character'),
        ),
    ]
