# Generated by Django 6.0.1 on 2026-02-06 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_quest_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enemy',
            name='armor',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='level',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='magic_armor',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='mana',
        ),
        migrations.AddField(
            model_name='enemy',
            name='is_defeated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enemy',
            name='max_health',
            field=models.IntegerField(default=500, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enemy',
            name='quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enemies', to='game.quest'),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='attack_power',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='health',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='xp_reward',
            field=models.IntegerField(),
        ),
    ]
