# Generated by Django 6.0.1 on 2026-02-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_remove_enemy_armor_remove_enemy_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enemy',
            name='is_defeated',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='max_health',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='quest',
        ),
        migrations.AddField(
            model_name='enemy',
            name='armor',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='enemy',
            name='level',
            field=models.IntegerField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='enemy',
            name='magic_armor',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='enemy',
            name='mana',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='attack_power',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='health',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='xp_reward',
            field=models.IntegerField(default=20),
        ),
    ]
