# Generated by Django 6.0.1 on 2026-02-06 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_remove_enemy_is_defeated_remove_enemy_max_health_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='is_defeated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enemy',
            name='quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enemies', to='game.quest'),
        ),
    ]
