# Generated by Django 6.0.1 on 2026-02-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_enemy_is_defeated_enemy_quest'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='max_health',
            field=models.IntegerField(default=100),
        ),
    ]
