# Generated by Django 6.0.1 on 2026-02-09 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_character_max_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_in_shop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='game.character'),
        ),
    ]
