# Generated by Django 6.0.1 on 2026-02-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_item_is_in_shop_item_price_alter_item_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='power',
            new_name='health_bonus',
        ),
        migrations.AddField(
            model_name='item',
            name='power_bonus',
            field=models.IntegerField(default=5),
        ),
    ]
