# Generated by Django 6.0.1 on 2026-02-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_rename_power_item_health_bonus_item_power_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('HEAD', 'Head'), ('CHEST', 'Chest'), ('FEET', 'Feet'), ('GLOVES', 'Gloves'), ('RING', 'Ring'), ('AMULET', 'Amulet'), ('WEAPON', 'Weapon')], default='WEAPON', max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='health_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='power_bonus',
            field=models.IntegerField(default=0),
        ),
    ]
