# Generated by Django 6.0.1 on 2026-02-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_item_item_type_alter_item_health_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_equipped',
            field=models.BooleanField(default=False),
        ),
    ]
